---
title: My dynamic report
output: html_fragment
---

{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)


{css}


Lancer Player Tendencies, A Dynamic Survey?

This is a survey on lancer player habits. You may contribute to this data via this google form and the data will be updated shortly after to reflect your results.

{r}
library(tidyverse)
library(magick)
logged_data <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTIHAfKioNot3iXEV3E7V1xZjqAUBx7TySN78jfEkHGU0eMxbJpt8O83NG1rOTZ041XLAc1o4hdbRTJ/pub?gid=97536103&single=true&output=csv")

latest_data <- logged_data %>% rename(years_played = 2,
                                      experience_level = 3,
                                      experience_type = 4,
                                      play_frequency = 5,
                                      campaign_activity = 6,
                                      modules_played = 7,
                                      other_massif = 8)

participant_count <- length(latest_data$years_played)

modules <- latest_data %>%separate_rows(modules_played, sep=", ")

# removing the count for the Siren's Song subtitle
modules <- modules[-which(modules$modules_played == "Mountain's Remorse"), ]

module_count <- modules%>%
  count(modules_played, name=NULL)

module_count[,1] <- c("None", "Dustgrave", "NRFaWF", "OSR", "OWS", "SoTW", "SSMR")

#null_index <- which(module_count$modules_played == NULL)

#finding min + max, while making sure to return all minimums rather than just the first

least_played_module <- module_count[which(module_count$n == min(module_count$n)), ]

most_played_module <- module_count[which(module_count$n == max(module_count$n)), ]

mean_modules_played <- sum(module_count$n)/participant_count

# Info Bar
image_blank(color="white", width=400, height=30)%>%
  image_annotate(text="Participation Count:", size =20, gravity="center")
image_blank(color="white", width=400, height=30)%>%
  image_annotate(text=participant_count, size =20, gravity="center")
image_blank(color="white", width=400, height=30)%>%
  image_annotate(text="Mean Playtime (years):", size =20, gravity="center")
image_blank(color="white", width=400, height=30)%>%
  image_annotate(text=mean(round(mean(latest_data$years_played)), digits = 2), size =20, gravity="center")

# Drawing Bar Charts

ggplot(data=module_count) +
  geom_col(aes(x=modules_played, y=n)) +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  labs(x="Module", y="Number of Players")


playtime_averages <- data.frame(c("Beginner", "Intermediate", "Veteran"),
                                c(mean((latest_data %>%subset(experience_level == "Beginner"))[,2]),
                                  mean((latest_data %>%subset(experience_level == "Intermediate Player"))[,2]),
                                  mean((latest_data %>%subset(experience_level == "Veteran"))[,2])))%>%
  rename(Confidence = 1,
         Playtime = 2)
ggplot(data=playtime_averages) +
  geom_col(aes(x=Confidence, y=Playtime)) +
  labs(y="Mean Years Played", x="Self-Described Skill Level")



